# Generated by Django 5.1.3 on 2025-08-18 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="name",
            field=models.CharField(
                choices=[
                    ("speaking", "Speaking"),
                    ("writing", "Writing"),
                    ("reading", "Reading"),
                    ("listening", "Listening"),
                    ("collaborative", "Collaborative Study"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="WhiteboardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="Whiteboard Session", max_length=200),
                ),
                ("image_data", models.TextField(help_text="Base64 encoded image data")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiteboards",
                        to="guide.simpleuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
