# Generated by Django 5.1.3 on 2025-08-19 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guide", "0002_alter_section_name_whiteboardimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpellingMistake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incorrect_word",
                    models.CharField(
                        help_text="The word you spelled incorrectly", max_length=100
                    ),
                ),
                (
                    "correct_word",
                    models.CharField(help_text="The correct spelling", max_length=100),
                ),
                (
                    "context",
                    models.TextField(
                        blank=True,
                        help_text="Sentence or context where you made the mistake",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Your notes about why you made this mistake",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1, help_text="How many times you've made this mistake"
                    ),
                ),
                (
                    "is_reviewed",
                    models.BooleanField(
                        default=False, help_text="Mark as reviewed after studying"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spelling_mistakes",
                        to="guide.simpleuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("user", "incorrect_word", "correct_word")},
            },
        ),
    ]
